name: Publishes Docker image to github registry

on:
  repository_dispatch:
    types: [build_image]

env:
  IMAGE_NAME: nestjs-sample-app

jobs: 
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
  
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      # Fetches all history for all branches and tags
      fetch-depth: 0
      # This is needed to push changes back to the repo
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Build image
    run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
  
  - name: Log in to registry
    run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
  - name: Push image
    run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
